version: '2'
services:

  ingress:
    extends:
      file: ./ingress/ingress.yml
      service: ingress
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.rule=Host(`localhost`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls.options=default'
      - 'traefik.http.routers.api.tls=true'

  mail:
    extends:
      file: ./mail/mail.yml
      service: mail

  # Test containers
  whoami1:
    image: containous/whoami
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.whoami1.rule=Host(`localhost`) && Path(`/whoami1`)"
      - "traefik.http.routers.whoami1.middlewares=whoami1-strip-prefix@docker,whoami1-testheader@docker"
      - "traefik.http.middlewares.whoami1-strip-prefix.stripprefix.prefixes=/whoami1"
      - "traefik.http.middlewares.whoami1-testheader.headers.customrequestheaders.X-Service-Name=whoami1"
  whoami2:
    image: containous/whoami
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.whoami2.rule=Host(`localhost`) && Path(`/whoami2`)"
      - "traefik.http.routers.whoami2.middlewares=whoami2-strip-prefix@docker,whoami2-testheader@docker"
      - "traefik.http.middlewares.whoami2-strip-prefix.stripprefix.prefixes=/whoami2"
      - "traefik.http.middlewares.whoami2-testheader.headers.customrequestheaders.X-Service-Name=whoami2"
