version: '2'
services:

  ingress:
    extends:
      file: ./ingress/ingress.yml
      service: ingress
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.rule=Host(`localhost`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls.options=default'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.middlewares.auth-proxy.forwardauth.address=http://auth-proxy:4456/decisions'
      - 'traefik.http.middlewares.auth-proxy.forwardauth.authResponseHeaders=X-User-Id'

  auth-proxy:
    extends:
      file: ./auth-proxy/auth-proxy.yml
      service: auth-proxy

  mail:
    extends:
      file: ./mail/mail.yml
      service: mail

  kratos-migrate:
    extends:
      file: ./identity-server/identity-server.yml
      service: kratos-migrate

  kratos:
    extends:
      file: ./identity-server/identity-server.yml
      service: kratos
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.kratos-admin-strip-prefix.stripprefix.prefixes=/kratos-admin'
      - 'traefik.http.middlewares.kratos-strip-prefix.stripprefix.prefixes=/kratos'
      - 'traefik.http.routers.kratos-admin.entrypoints=https'
      - 'traefik.http.routers.kratos-admin.middlewares=kratos-admin-strip-prefix@docker'
      - 'traefik.http.routers.kratos-admin.rule=Host(`localhost`) && PathPrefix(`/kratos-admin`)'
      - 'traefik.http.routers.kratos-admin.service=kratos-admin'
      - 'traefik.http.routers.kratos-admin.tls.options=default'
      - 'traefik.http.routers.kratos-admin.tls=true'
      - 'traefik.http.routers.kratos.entrypoints=https'
      - 'traefik.http.routers.kratos.middlewares=kratos-strip-prefix@docker'
      - 'traefik.http.routers.kratos.rule=Host(`localhost`) && PathPrefix(`/kratos`)'
      - 'traefik.http.routers.kratos.service=kratos'
      - 'traefik.http.routers.kratos.tls.options=default'
      - 'traefik.http.routers.kratos.tls=true'
      - 'traefik.http.services.kratos-admin.loadbalancer.server.port=4434'
      - 'traefik.http.services.kratos.loadbalancer.server.port=4433'

  website:
    extends:
      file: ./website/website.yml
      service: website
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.website-strip-prefix.stripprefix.prefixes=/website'
      - 'traefik.http.routers.website.entrypoints=https'
      - 'traefik.http.routers.website.middlewares=auth-proxy@docker,website-strip-prefix@docker'
      - 'traefik.http.routers.website.rule=Host(`localhost`) && PathPrefix(`/website/`)'
      - 'traefik.http.routers.website.service=website'
      - 'traefik.http.routers.website.tls.options=default'
      - 'traefik.http.routers.website.tls=true'
      - 'traefik.http.services.website.loadbalancer.server.port=4455'

  whoami:
    image: containous/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.entrypoints=https'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.routers.whoami.tls.options=default'
      - "traefik.http.routers.whoami.rule=Host(`localhost`) && (Path(`/whoami`) || Path(`/whoami-protected`))"
      - "traefik.http.routers.whoami.middlewares=auth-proxy@docker,whoami-strip-prefix@docker"
      - "traefik.http.middlewares.whoami-strip-prefix.stripprefix.prefixes=/whoami-protected,/whoami"
