global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
providers:
  docker:
    exposedByDefault: true
api:
  dashboard: true
  debug: true
log:
  level: debug
